### ISSUE TITLE
MXS doesn't find the XSS in the HTML response

### ISSUE THREAD

**Issue by qu35t-code** [sarperavci/MXS#10]
Hello,

I'm having a problem using this tool. For testing purposes, I use **PortSwigger's XSS reflected lab** : https://portswigger.net/web-security/cross-site-scripting/reflected/lab-html-context-nothing-encoded

I added this link in a `t.txt` file.

```bash
https://0a170095045518cb8594bf1400550000.web-security-academy.net/?search=ds
```

The tool does not find the classic reflected XSS :

`https://0a170095045518cb8594bf1400550000.web-security-academy.net/?search=<script>alert(1)</script>`

```bash
python3 MXS.py -i t.txt -o results.txt
 [i] Starting scan with 50 concurrency
 [i] Output file: results.txt
 [i] Timeout: 15 seconds
 [i] Scanning finished. All URLs are saved to results.txt
 [i] Total found: 0
 [i] Total scanned: 1
 [i] Time taken: 0 seconds
```

On the other hand, the lab is well solved, so the tool's payloads are fully functional, it's the XSS validation function that's not working properly.

<img width="1299" alt="image" src="https://github.com/user-attachments/assets/f6a5fd80-9626-4d69-a02c-663c13d8cb18">

**Comment by M-Enes** [comment]
Hello.

It seems like there is no problem with mxs's payloads or working mechanism.

I guess when xss payload sent, Portswigger lab statically analyzes it or runs it in a sandboxed environment. Then, if the expected output found, it means that the lab solved.

Could you manually test the mxs's polyglot payload and share the result of that payload?

**Comment by sarperavci** [comment]
Given the wide use of [RFC 3986](https://en.wikipedia.org/wiki/Percent-encoding#Reserved_characters), the URL encoding standard that requires certain special characters to be encoded, testing MXS or any automatic scanner in _a context where nothing is encoded_ is not a good idea. Our tool heavily encodes payloads.

There are very few websites that do not comply with modern standards. Nevertheless, we know we need to improve our check mechanism because it currently performs a primitive check.
